import './globals.css';
import { Playfair_Display } from 'next/font/google';
const playfair = Playfair_Display({ subsets: ['latin'] });

export const metadata = {
    title: 'Varshith Portfolio',
    description: 'Generated by varshith',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={playfair.className}>
            <body>{children}</body>
        </html>
    );
}
